import numpy
import pandas
import sklearn
import xgboost
import catboost
import joblib
import fastapi
import uvicorn
import pydantic
import streamlit
import requests

print("numpy:", numpy.__version__)
print("pandas:", pandas.__version__)
print("scikit-learn:", sklearn.__version__)
print("xgboost:", xgboost.__version__)
print("catboost:", catboost.__version__)
print("joblib:", joblib.__version__)
print("fastapi:", fastapi.__version__)
print("uvicorn:", uvicorn.__version__)
print("pydantic:", pydantic.__version__)
print("streamlit:", streamlit.__version__)
print("requests:", requests.__version__)